package meet_at_mensa.matching.model;

// import persistence tags
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

// import utils
import java.util.UUID;

// Class Timeslot represents a single entry (row) in the matchdb/match_timeslots
@Entity
@Table(name = "prompts")
public class Prompt {
    
    // ----------
    // Attributes
    // (Each attribute here corresponds to one column in the MySQL matchdb/match_timeslots table)
    // ----------

    // Auto-generated unique ID for this Match request
    @Id
    @GeneratedValue(strategy=GenerationType.UUID)
    @Column(name = "prompt_id")
    private UUID promptID;
    
    @Column(name = "group_id")
    private UUID groupID;

    @Column(name = "prompt")
    private String prompt;

    // -------
    // Getters
    // -------

    public UUID getPromptID() {
        return promptID;
    }
    
    public UUID getGroupID() {
        return groupID;
    }
    
    public String getPrompt() {
        return prompt;
    }

    // -------
    // Setters
    // -------

    // no setters for
    // - PromptID (autogenerated)
    
    public void setGroupID(UUID requestID) {
        this.groupID = requestID;
    }
    
    public void setPrompt(String prompt) {
        this.prompt = prompt;
    }

    // ------------
    // Constructors
    // ------------

    public Prompt() {

        // default constructor required by JPA

    }

    public Prompt(UUID groupID, String prompt) {

        this.groupID = groupID;
        this.prompt = prompt;

    }

    // ------------
    // Others
    // ------------

}


