package meet_at_mensa.matching.model;

// import persistence tags
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

// import utils
import java.util.UUID;

// Class Timeslot represents a single entry (row) in the matchdb/match_timeslots
@Entity
@Table(name = "match_timeslots")
public class TimeslotEntity {
    
    // ----------
    // Attributes
    // (Each attribute here corresponds to one column in the MySQL matchdb/match_timeslots table)
    // ----------

    // Auto-generated unique ID for this Match request
    @Id
    @GeneratedValue(strategy=GenerationType.UUID)
    @Column(name = "timeslot_id")
    private UUID timeslotID;
    
    @Column(name = "request_id")
    private UUID requestID;

    @Column(name = "request_timeslot")
    private Integer timeslot;

    // -------
    // Getters
    // -------

    public UUID getTimeslotID() {
        return timeslotID;
    }
    
    public UUID getRequestID() {
        return requestID;
    }
    
    public Integer getTimeslot() {
        return timeslot;
    }

    // -------
    // Setters
    // -------

    // no setters for
    // - TimeslotID (autogenerated)
    
    public void setRequestID(UUID requestID) {
        this.requestID = requestID;
    }
    
    public void setTimeslot(Integer timeslot) {
        this.timeslot = timeslot;
    }

    // ------------
    // Constructors
    // ------------

    public TimeslotEntity() {

        // default constructor required by JPA

    }

    public TimeslotEntity(UUID requestID, Integer timeslot) {

        this.requestID = requestID;
        this.timeslot = timeslot;

    }

    // ------------
    // Others
    // ------------

}

