apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring-test
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.26.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: 9093

          volumeMounts:
            - name: alertmanager-config-volume
              mountPath: /etc/alertmanager/
      volumes:
        - name: alertmanager-config-volume
          configMap:
            name: alertmanager-config 