apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring-test
data:
  alertmanager.yml: |
    route:
      receiver: 'telegram-notifications'
    receivers:
      - name: 'telegram-notifications'
        telegram_configs:
          - bot_token: '7501998830:AAHQxS2sHnL9wgYIVKx05VbHWBwgZMpqwgg'
            chat_id: -4843405053
            message: |
              **ALERT TEMPLATE TEST**
              {{ range .Alerts }}
              Alert: {{ .Labels.alertname }}
              Summary: {{ .Annotations.summary }}
              {{ end }}
            parse_mode: 'Markdown'
            send_resolved: true 