apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: go76taw-devops25
data:
  grafana.ini: |
    [server]
    http_port = 3000

    [security]
    admin_user = admin
    admin_password = admin

    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
