apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-rules
  namespace: monitoring-test
data:
  microservices-up-alerts.yaml: |
    apiVersion: 1
    groups:
      - name: microservices-up
        folder: Provisioned Alerts
        interval: 1m
        rules:
          - uid: "microservices-up-alert"
            title: "Microservice Down"
            condition: "A"
            data:
              - refId: A
                queryType: "timeSeriesQuery"
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: "Prometheus"
                model:
                  expr: sum(up{instance=~"meetatmensa-gateway:8080|meetatmensa-genai:80|meetatmensa-matching:80|meetatmensa-user:80"}) < 4
                  interval: ""
                  datasource:
                    type: "prometheus"
                    uid: "Prometheus"
            noDataState: "Alerting"
            execErrState: "Error"
            for: 1s
            annotations:
              summary: "A monitored microservice is down"
              description: "At least one of the main microservices (gateway, matching, user, genai) is not up."
            labels:
              severity: "critical"
            notifications:
              - name: "alertmanager" 