apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring-test
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        fsGroup: 472
      initContainers:
        - name: wipe-grafana-data
          image: busybox
          command: ["sh", "-c", "rm -rf /var/lib/grafana/*"]
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      containers:
        - name: grafana
          image: grafana/grafana:10.2.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
            - name: grafana-storage
              mountPath: /var/lib/grafana

            - name: grafana-contact-points
              mountPath: /etc/grafana/provisioning/contact-points
            - name: grafana-notification-policies
              mountPath: /etc/grafana/provisioning/notification-policies
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboard-provisioning
          configMap:
            name: grafana-dashboard-provisioning
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboard-prometheus
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc

        - name: grafana-contact-points
          configMap:
            name: grafana-contact-points
        - name: grafana-notification-policies
          configMap:
            name: grafana-notification-policies
