apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-policies
  namespace: monitoring-test
data:
  notification-policies.yaml: |
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: alertmanager
        group_by: ['alertname']
        routes: [] 