apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: go76taw-testing
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: init-loki-dir
          image: busybox
          command:
            [
              "sh",
              "-c",
              "mkdir -p /loki /loki/chunks /loki/index /loki/index_cache /loki/compactor",
            ]
          volumeMounts:
            - name: loki-storage
              mountPath: /loki
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: loki
          image: grafana/loki:2.9.2
          args:
            - -config.file=/etc/loki/loki-config.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki-config.yaml
              subPath: loki-config.yaml
            - name: loki-storage
              mountPath: /loki
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
