apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: app-podmonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      monitoring: "true"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: http
      interval: 30s 