apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: go76taw-testing
  labels:
    app: promtail
spec:
  selector:
    app: promtail
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  type: ClusterIP
