apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    app: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: prometheus 