apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      monitoring: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      interval: 30s 