apiVersion: v1
kind: Pod
metadata:
  name: test-loki-pvc
  namespace: go76taw-testing
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: loki-storage
          mountPath: /loki
  volumes:
    - name: loki-storage
      persistentVolumeClaim:
        claimName: loki-pvc
