/*
 * MeetAtMensa
 * This OpenAPI specification defines the endpoints, schemas, and security mechanisms for the Meet@Mensa User micro-service. 
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: devoops@tyrean.mozmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Object Representing a set of user preferences
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-01T14:30:52.811533401Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class MatchPreferences {
  public static final String SERIALIZED_NAME_DEGREE_PREF = "degreePref";
  @SerializedName(SERIALIZED_NAME_DEGREE_PREF)
  @javax.annotation.Nonnull
  private Boolean degreePref;

  public static final String SERIALIZED_NAME_AGE_PREF = "agePref";
  @SerializedName(SERIALIZED_NAME_AGE_PREF)
  @javax.annotation.Nonnull
  private Boolean agePref;

  public static final String SERIALIZED_NAME_GENDER_PREF = "genderPref";
  @SerializedName(SERIALIZED_NAME_GENDER_PREF)
  @javax.annotation.Nonnull
  private Boolean genderPref;

  public MatchPreferences() {
  }

  public MatchPreferences degreePref(@javax.annotation.Nonnull Boolean degreePref) {
    this.degreePref = degreePref;
    return this;
  }

  /**
   * Value | Meaning  ---------|---------  true | degree &#x3D; same (priority)  false | degree &#x3D; any (no priority)
   * @return degreePref
   */
  @javax.annotation.Nonnull
  public Boolean getDegreePref() {
    return degreePref;
  }

  public void setDegreePref(@javax.annotation.Nonnull Boolean degreePref) {
    this.degreePref = degreePref;
  }


  public MatchPreferences agePref(@javax.annotation.Nonnull Boolean agePref) {
    this.agePref = agePref;
    return this;
  }

  /**
   * Value | Meaning  ---------|---------  true | age &#x3D; same (priority)  false | age &#x3D; any (no priority)
   * @return agePref
   */
  @javax.annotation.Nonnull
  public Boolean getAgePref() {
    return agePref;
  }

  public void setAgePref(@javax.annotation.Nonnull Boolean agePref) {
    this.agePref = agePref;
  }


  public MatchPreferences genderPref(@javax.annotation.Nonnull Boolean genderPref) {
    this.genderPref = genderPref;
    return this;
  }

  /**
   * Value | Meaning  ---------|---------  true | gender &#x3D; same (priority)  false | gender &#x3D; any (no priority)
   * @return genderPref
   */
  @javax.annotation.Nonnull
  public Boolean getGenderPref() {
    return genderPref;
  }

  public void setGenderPref(@javax.annotation.Nonnull Boolean genderPref) {
    this.genderPref = genderPref;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchPreferences matchPreferences = (MatchPreferences) o;
    return Objects.equals(this.degreePref, matchPreferences.degreePref) &&
        Objects.equals(this.agePref, matchPreferences.agePref) &&
        Objects.equals(this.genderPref, matchPreferences.genderPref);
  }

  @Override
  public int hashCode() {
    return Objects.hash(degreePref, agePref, genderPref);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchPreferences {\n");
    sb.append("    degreePref: ").append(toIndentedString(degreePref)).append("\n");
    sb.append("    agePref: ").append(toIndentedString(agePref)).append("\n");
    sb.append("    genderPref: ").append(toIndentedString(genderPref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("degreePref", "agePref", "genderPref"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("degreePref", "agePref", "genderPref"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MatchPreferences
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MatchPreferences.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MatchPreferences is not found in the empty JSON string", MatchPreferences.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MatchPreferences.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MatchPreferences` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MatchPreferences.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MatchPreferences.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MatchPreferences' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MatchPreferences> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MatchPreferences.class));

       return (TypeAdapter<T>) new TypeAdapter<MatchPreferences>() {
           @Override
           public void write(JsonWriter out, MatchPreferences value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MatchPreferences read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MatchPreferences given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MatchPreferences
   * @throws IOException if the JSON string is invalid with respect to MatchPreferences
   */
  public static MatchPreferences fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MatchPreferences.class);
  }

  /**
   * Convert an instance of MatchPreferences to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

