/*
 * MeetAtMensa
 * This OpenAPI specification defines the endpoints, schemas, and security mechanisms for the Meet@Mensa User micro-service. 
 *
 * The version of the OpenAPI document: 2.2.2
 * Contact: devoops@tyrean.mozmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Object representing a student user in the Meet@Mensa system.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-19T14:23:43.639048386Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class UserNew {
  public static final String SERIALIZED_NAME_AUTH_I_D = "authID";
  @SerializedName(SERIALIZED_NAME_AUTH_I_D)
  @javax.annotation.Nonnull
  private String authID;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nonnull
  private String email;

  public static final String SERIALIZED_NAME_FIRSTNAME = "firstname";
  @SerializedName(SERIALIZED_NAME_FIRSTNAME)
  @javax.annotation.Nonnull
  private String firstname;

  public static final String SERIALIZED_NAME_LASTNAME = "lastname";
  @SerializedName(SERIALIZED_NAME_LASTNAME)
  @javax.annotation.Nonnull
  private String lastname;

  public static final String SERIALIZED_NAME_BIRTHDAY = "birthday";
  @SerializedName(SERIALIZED_NAME_BIRTHDAY)
  @javax.annotation.Nonnull
  private LocalDate birthday;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  @javax.annotation.Nonnull
  private String gender = "other";

  public static final String SERIALIZED_NAME_DEGREE = "degree";
  @SerializedName(SERIALIZED_NAME_DEGREE)
  @javax.annotation.Nonnull
  private String degree;

  public static final String SERIALIZED_NAME_DEGREE_START = "degreeStart";
  @SerializedName(SERIALIZED_NAME_DEGREE_START)
  @javax.annotation.Nonnull
  private Integer degreeStart;

  public static final String SERIALIZED_NAME_INTERESTS = "interests";
  @SerializedName(SERIALIZED_NAME_INTERESTS)
  @javax.annotation.Nonnull
  private List<String> interests = new ArrayList<>();

  public static final String SERIALIZED_NAME_BIO = "bio";
  @SerializedName(SERIALIZED_NAME_BIO)
  @javax.annotation.Nonnull
  private String bio;

  public UserNew() {
  }

  public UserNew authID(@javax.annotation.Nonnull String authID) {
    this.authID = authID;
    return this;
  }

  /**
   * Auth0 user.sub, used as a unique key  
   * @return authID
   */
  @javax.annotation.Nonnull
  public String getAuthID() {
    return authID;
  }

  public void setAuthID(@javax.annotation.Nonnull String authID) {
    this.authID = authID;
  }


  public UserNew email(@javax.annotation.Nonnull String email) {
    this.email = email;
    return this;
  }

  /**
   * Users&#39;s e-mail
   * @return email
   */
  @javax.annotation.Nonnull
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
  }


  public UserNew firstname(@javax.annotation.Nonnull String firstname) {
    this.firstname = firstname;
    return this;
  }

  /**
   * User&#39;s given name
   * @return firstname
   */
  @javax.annotation.Nonnull
  public String getFirstname() {
    return firstname;
  }

  public void setFirstname(@javax.annotation.Nonnull String firstname) {
    this.firstname = firstname;
  }


  public UserNew lastname(@javax.annotation.Nonnull String lastname) {
    this.lastname = lastname;
    return this;
  }

  /**
   * User&#39;s surname
   * @return lastname
   */
  @javax.annotation.Nonnull
  public String getLastname() {
    return lastname;
  }

  public void setLastname(@javax.annotation.Nonnull String lastname) {
    this.lastname = lastname;
  }


  public UserNew birthday(@javax.annotation.Nonnull LocalDate birthday) {
    this.birthday = birthday;
    return this;
  }

  /**
   * User&#39;s date of birth
   * @return birthday
   */
  @javax.annotation.Nonnull
  public LocalDate getBirthday() {
    return birthday;
  }

  public void setBirthday(@javax.annotation.Nonnull LocalDate birthday) {
    this.birthday = birthday;
  }


  public UserNew gender(@javax.annotation.Nonnull String gender) {
    this.gender = gender;
    return this;
  }

  /**
   * User&#39;s gender
   * @return gender
   */
  @javax.annotation.Nonnull
  public String getGender() {
    return gender;
  }

  public void setGender(@javax.annotation.Nonnull String gender) {
    this.gender = gender;
  }


  public UserNew degree(@javax.annotation.Nonnull String degree) {
    this.degree = degree;
    return this;
  }

  /**
   * User&#39;s degree program
   * @return degree
   */
  @javax.annotation.Nonnull
  public String getDegree() {
    return degree;
  }

  public void setDegree(@javax.annotation.Nonnull String degree) {
    this.degree = degree;
  }


  public UserNew degreeStart(@javax.annotation.Nonnull Integer degreeStart) {
    this.degreeStart = degreeStart;
    return this;
  }

  /**
   * What year User started their degree
   * minimum: 2000
   * maximum: 2100
   * @return degreeStart
   */
  @javax.annotation.Nonnull
  public Integer getDegreeStart() {
    return degreeStart;
  }

  public void setDegreeStart(@javax.annotation.Nonnull Integer degreeStart) {
    this.degreeStart = degreeStart;
  }


  public UserNew interests(@javax.annotation.Nonnull List<String> interests) {
    this.interests = interests;
    return this;
  }

  public UserNew addInterestsItem(String interestsItem) {
    if (this.interests == null) {
      this.interests = new ArrayList<>();
    }
    this.interests.add(interestsItem);
    return this;
  }

  /**
   * Array of a User&#39;s interests
   * @return interests
   */
  @javax.annotation.Nonnull
  public List<String> getInterests() {
    return interests;
  }

  public void setInterests(@javax.annotation.Nonnull List<String> interests) {
    this.interests = interests;
  }


  public UserNew bio(@javax.annotation.Nonnull String bio) {
    this.bio = bio;
    return this;
  }

  /**
   * Short introduction text written by the user
   * @return bio
   */
  @javax.annotation.Nonnull
  public String getBio() {
    return bio;
  }

  public void setBio(@javax.annotation.Nonnull String bio) {
    this.bio = bio;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserNew userNew = (UserNew) o;
    return Objects.equals(this.authID, userNew.authID) &&
        Objects.equals(this.email, userNew.email) &&
        Objects.equals(this.firstname, userNew.firstname) &&
        Objects.equals(this.lastname, userNew.lastname) &&
        Objects.equals(this.birthday, userNew.birthday) &&
        Objects.equals(this.gender, userNew.gender) &&
        Objects.equals(this.degree, userNew.degree) &&
        Objects.equals(this.degreeStart, userNew.degreeStart) &&
        Objects.equals(this.interests, userNew.interests) &&
        Objects.equals(this.bio, userNew.bio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authID, email, firstname, lastname, birthday, gender, degree, degreeStart, interests, bio);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserNew {\n");
    sb.append("    authID: ").append(toIndentedString(authID)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    degree: ").append(toIndentedString(degree)).append("\n");
    sb.append("    degreeStart: ").append(toIndentedString(degreeStart)).append("\n");
    sb.append("    interests: ").append(toIndentedString(interests)).append("\n");
    sb.append("    bio: ").append(toIndentedString(bio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("authID", "email", "firstname", "lastname", "birthday", "gender", "degree", "degreeStart", "interests", "bio"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("authID", "email", "firstname", "lastname", "birthday", "gender", "degree", "degreeStart", "interests", "bio"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UserNew
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UserNew.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UserNew is not found in the empty JSON string", UserNew.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UserNew.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UserNew` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UserNew.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("authID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `authID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authID").toString()));
      }
      if (!jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if (!jsonObj.get("firstname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstname").toString()));
      }
      if (!jsonObj.get("lastname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastname").toString()));
      }
      if (!jsonObj.get("gender").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gender` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gender").toString()));
      }
      if (!jsonObj.get("degree").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `degree` to be a primitive type in the JSON string but got `%s`", jsonObj.get("degree").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("interests") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("interests").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `interests` to be an array in the JSON string but got `%s`", jsonObj.get("interests").toString()));
      }
      if (!jsonObj.get("bio").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bio` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bio").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserNew.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserNew' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserNew> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserNew.class));

       return (TypeAdapter<T>) new TypeAdapter<UserNew>() {
           @Override
           public void write(JsonWriter out, UserNew value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UserNew read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UserNew given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UserNew
   * @throws IOException if the JSON string is invalid with respect to UserNew
   */
  public static UserNew fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserNew.class);
  }

  /**
   * Convert an instance of UserNew to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

