apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-config
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  grafana.ini: |
    [server]
    http_port = 3000
    
    [security]
    admin_user = {{ .Values.grafana.adminUser }}
    admin_password = {{ .Values.grafana.adminPassword }}
    
    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db
    
    [session]
    provider = file
    provider_config = sessions
    
    [log]
    mode = console
    level = info
    
    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning 