/*
 * MeetAtMensa
 * This OpenAPI specification defines the endpoints, schemas, and security mechanisms for the Meet@Mensa User micro-service. 
 *
 * The version of the OpenAPI document: 2.1.4
 * Contact: devoops@tyrean.mozmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MatchPreferences
 */
public class MatchPreferencesTest {
    private final MatchPreferences model = new MatchPreferences();

    /**
     * Model tests for MatchPreferences
     */
    @Test
    public void testMatchPreferences() {
        // TODO: test MatchPreferences
    }

    /**
     * Test the property 'degreePref'
     */
    @Test
    public void degreePrefTest() {
        // TODO: test degreePref
    }

    /**
     * Test the property 'agePref'
     */
    @Test
    public void agePrefTest() {
        // TODO: test agePref
    }

    /**
     * Test the property 'genderPref'
     */
    @Test
    public void genderPrefTest() {
        // TODO: test genderPref
    }

}
