all:
  hosts:
    app_server:
      ansible_host: "{{ lookup('env', 'EC2_PUBLIC_IP') }}"
      ansible_user: "{{ lookup('env', 'AWS_EC2_USER') }}"
      ansible_ssh_private_key: "{{ lookup('env', 'AWS_EC2_PRIVATE_KEY') }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
