all:
  hosts:
    app_server:
      ansible_host: "{{ ansible_host }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: vockey.pem
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
