all:
  hosts:
    app_server:
      ansible_host: "{{ EC2_PUBLIC_IP }}"
      ansible_user: "{{ AWS_EC2_USER }}"
      ansible_ssh_private_key: "{{ AWS_EC2_PRIVATE_KEY }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
