global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'meetatmensa-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['meetatmensa-gateway:8080']

  - job_name: 'meetatmensa-matching'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['meetatmensa-matching:80']

  - job_name: 'meetatmensa-user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['meetatmensa-user:80']

  - job_name: 'meetatmensa-genai'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['meetatmensa-genai:80']