apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: P8E80F9AEF21F6940
    isDefault: false
    jsonData:
      maxLines: 1000
      httpMethod: POST
    version: 1