apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "matchdb.fullname" . }}-pvc
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
