apiVersion: v1
kind: Service
metadata:
  name: {{ include "userdb.fullname" . }}
  labels:
    {{- include "userdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "userdb.selectorLabels" . | nindent 4 }}
