apiVersion: v1
kind: Service
metadata:
  name: {{ include "userdb.fullname" . }}
  labels:
    {{- include "userdb.labels" . | nindent 4 }}
    # Monitoring and label-based discovery labels
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "userdb.selectorLabels" . | nindent 4 }}
