# This file is used to deploy the microservices using Docker Compose.
# It defines the services, their images, build context, and ports.

services:
  gateway-service:
    build: ../server/gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - chat-service
      - matching-service
      - user-service
    networks:
      - backend

  chat-service:
    build: ../server/chat
    container_name: chat-service
    expose:
      - "80"
    networks:
      - backend

  matching-service:
    build: ../server/matching
    container_name: matching-service
    expose:
      - "80"
    networks:
      - backend

  user-service:
    build: ../server/user
    container_name: user-service
    expose:
      - "80"
    networks:
      - backend

  genai-service:
    build: ../genai
    container_name: genai-service
    expose:
      - "80"
    networks:
      - backend

networks:
  backend:
    driver: bridge