---
- name: Test basic connectivity
  hosts: app_server
  gather_facts: yes
  tasks:
    - name: Test connection
      ping:

- name: Install system packages
  hosts: app_server
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

- name: Setup Docker
  hosts: app_server
  become: yes
  tasks:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Verify Docker repository was added
      shell: apt-cache policy docker-ce
      register: docker_repo_check
      changed_when: false

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

- name: Configure Docker
  hosts: app_server
  become: yes
  tasks:
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

- name: Deploy application
  hosts: app_server
  become: yes
  vars:
    app_user: "{{ ansible_user }}"
    app_dir: "/home/{{ app_user }}"
    deployment_dir: "{{ app_dir }}/deployment"

  tasks:
    - name: Create deployment directory
      file:
        path: "{{ deployment_dir }}"
        state: directory
        mode: "0755"

    - name: Copy docker-compose file
      copy:
        src: ../../deployment/compose.aws.yml
        dest: "{{ deployment_dir }}/compose.aws.yml"
        mode: "0644"

    - name: Create .env.prod file
      template:
        src: ../templates/env.prod.j2
        dest: "{{ app_dir }}/.env.prod"
        mode: "0644"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ deployment_dir }}"
        files:
          - compose.aws.yml
        state: present
        build: yes
        remove_orphans: yes
      environment:
        DOCKER_BUILDKIT: 1
