---
- name: Test basic connectivity
  hosts: app_server
  gather_facts: yes
  tasks:
    - name: Test connection
      ping:

- name: Install system packages
  hosts: app_server
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

- name: Setup Docker
  hosts: app_server
  become: yes
  vars:
    docker_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
  tasks:
    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

- name: Configure Docker
  hosts: app_server
  become: yes
  tasks:
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

- name: Deploy application
  hosts: app_server
  become: yes
  vars:
    app_user: "{{ ansible_user }}"
    app_dir: "/home/{{ app_user }}"
    deployment_dir: "{{ app_dir }}/deployment"

  tasks:
    - name: Create deployment directory
      file:
        path: "{{ deployment_dir }}"
        state: directory
        mode: "0755"

    - name: Copy docker-compose file
      copy:
        src: "{{ playbook_dir }}/../../../deployment/compose.aws.yml"
        dest: "{{ deployment_dir }}/compose.aws.yml"
        mode: "0644"

    - name: Create .env.prod file 
      template:
        src: "{{ playbook_dir }}/../templates/env.prod.j2"
        dest: "{{ app_dir }}/.env.prod"
        mode: "0644"

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ deployment_dir }}"
        files:
          - compose.aws.yml
        state: present
        build: always
        remove_orphans: yes
      environment:
        DOCKER_BUILDKIT: 1
        EC2_PUBLIC_IP: "{{ ansible_host }}"
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}