/*
 * MeetAtMensa
 * This OpenAPI specification defines the endpoints, schemas, and security mechanisms for the Meet@Mensa User micro-service. 
 *
 * The version of the OpenAPI document: 2.1.4
 * Contact: devoops@tyrean.mozmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ConversationStarter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConversationStarterCollection
 */
public class ConversationStarterCollectionTest {
    private final ConversationStarterCollection model = new ConversationStarterCollection();

    /**
     * Model tests for ConversationStarterCollection
     */
    @Test
    public void testConversationStarterCollection() {
        // TODO: test ConversationStarterCollection
    }

    /**
     * Test the property 'conversationsStarters'
     */
    @Test
    public void conversationsStartersTest() {
        // TODO: test conversationsStarters
    }

}
