/*
 * MeetAtMensa
 * This OpenAPI specification defines the endpoints, schemas, and security mechanisms for the Meet@Mensa User micro-service. 
 *
 * The version of the OpenAPI document: 2.1.4
 * Contact: devoops@tyrean.mozmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.ConversationStarterCollection;
import org.openapitools.client.model.Location;
import org.openapitools.client.model.MatchStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Group
 */
public class GroupTest {
    private final Group model = new Group();

    /**
     * Model tests for Group
     */
    @Test
    public void testGroup() {
        // TODO: test Group
    }

    /**
     * Test the property 'groupID'
     */
    @Test
    public void groupIDTest() {
        // TODO: test groupID
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'userStatus'
     */
    @Test
    public void userStatusTest() {
        // TODO: test userStatus
    }

    /**
     * Test the property 'conversationStarters'
     */
    @Test
    public void conversationStartersTest() {
        // TODO: test conversationStarters
    }

}
