# This file is used to deploy the microservices using Docker Compose.
# It defines the services, their images, build context, and ports.

services:
  gateway-service:
    build: ../../server/gateway
    container_name: meetatmensa-gateway
    ports:
      - "8080:80"
    depends_on:
      - chat-service
      - matching-service
      - user-service
      - genai-service
    networks:
      - backend

  chat-service:
    build: ../../server/chat
    container_name: meetatmensa-chat
    expose:
      - "80"
    depends_on:
      - chat-database
    networks:
      - backend

  matching-service:
    build: ../../server/matching
    container_name: meetatmensa-matching
    expose:
      - "80"
    depends_on:
      - match-database
    networks:
      - backend

  user-service:
    build: ../../server/user
    container_name: meetatmensa-user
    expose:
      - "80"
    depends_on:
      - user-database
    networks:
      - backend

  genai-service:
    build: ../../genai
    container_name: meetatmensa-genai
    expose:
      - "80"
    networks:
      - backend

  client-service:
    build: ../../client
    container_name: meetatmensa-client
    ports:
      - "80:80"

  chat-database:
    build: ../../database/chatdb
    container_name: meetatmensa-chatdb
    # TODO: Implement password passed via secret
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306:3306"
    networks:
      - backend

  match-database:
    build: ../../database/matchdb
    container_name: meetatmensa-matchdb
    # TODO: Implement password passed via secret
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3307:3306"
    networks:
      - backend

  user-database:
    build: ../../database/userdb
    container_name: meetatmensa-userdb
    # TODO: Implement password passed via secret
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3308:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge