# This file is used to deploy the microservices using Docker Compose.
# It defines the services, their images, build context, and ports.

services:
  gateway-service:
    build: ../../server/gateway
    container_name: meetatmensa-gateway
    ports:
      - "8080:80"
    depends_on:
      - chat-service
      - matching-service
      - user-service
      - genai-service
    networks:
      - backend

  chat-service:
    build: ../../server/chat
    container_name: meetatmensa-chat
    expose:
      - "80"
    networks:
      - backend

  matching-service:
    build: ../../server/matching
    container_name: meetatmensa-matching
    expose:
      - "80"
    networks:
      - backend

  user-service:
    build: ../../server/user
    container_name: meetatmensa-user
    expose:
      - "80"
    networks:
      - backend

  genai-service:
    build: ../../genai
    container_name: meetatmensa-genai
    expose:
      - "80"
    networks:
      - backend

  client-service:
    build: ../../client
    container_name: meetatmensa-client
    ports:
      - "80:80"

networks:
  backend:
    driver: bridge