# This file is used to deploy the microservices using Docker Compose.
# It defines the services, their images, build context, and ports.

services:
  meetatmensa-gateway:
    build: ../../server/gateway
    container_name: meetatmensa-gateway
    ports:
      - "8080:8080"
    depends_on:
      - meetatmensa-matching
      - meetatmensa-user
      - meetatmensa-genai
    networks:
      - backend

  meetatmensa-matching:
    build: ../../server/matching
    container_name: meetatmensa-matching
    expose:
      - "80"
    depends_on:
      - match-database
    networks:
      - backend

  meetatmensa-user:
    build: ../../server/user
    container_name: meetatmensa-user
    expose:
      - "80"
    depends_on:
      - user-database
    networks:
      - backend

  meetatmensa-genai:
    build: ../../server/genai
    container_name: meetatmensa-genai
    expose:
      - "80"
    networks:
      - backend
    env_file:
      - .env

  meetatmensa-client:
    build: 
      context: ../../client
    container_name: meetatmensa-client
    ports:
      - "80:80"
    environment:
      - API_BASE_URL=http://localhost:8080

  match-database:
    build: ../../server/database/matchdb
    container_name: meetatmensa-matchdb
    # TODO: Implement password passed via secret
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - matchdb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - backend

  user-database:
    build: ../../server/database/userdb
    container_name: meetatmensa-userdb
    # TODO: Implement password passed via secret
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - userdb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  matchdb_data:
  userdb_data: