# k8s/values.yaml
ingress:
  enabled: true
  gatewayServiceName: meetatmensa-gateway
  gatewayHost: api.meetatmensa.com
  clientServiceName: meetatmensa-client
  clientHost: app.meetatmensa.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx

gateway:
  ingress:
    enabled: false
  service:
    port: 8080


client:
  ingress:
    enabled: false
  service:
    port: 80