# This configuration file defines the routing rules for the Spring Cloud Gateway
# and specifies the backend services to which requests should be forwarded.
server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-noniz4lq6jsgl8r6.us-5.auth0.com/
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: 
                - "http://localhost"
                - "http://127.0.0.1"
                - "http://localhost:80"
                - "http://127.0.0.1:80"
                - "http://localhost:8080"
                - "http://127.0.0.1:8080"
                - "https://app.meetatmensa.com"
                - "http://app.meetatmensa.com"
                - "https://client.54.204.29.206.sslip.io"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: 
                - "*"
      routes:
        - id: matching_route
          uri: http://meetatmensa-matching:80
          predicates:
            - Path=/api/v2/matching/**

        - id: user_route
          uri: http://meetatmensa-user:80
          predicates:
            - Path=/api/v2/user/**

        - id: genai_route
          uri: http://meetatmensa-genai:80
          predicates:
            - Path=/genai/**
