# This configuration file defines the routing rules for the Spring Cloud Gateway
# and specifies the backend services to which requests should be forwarded.
server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: matching_route
          uri: http://meetatmensa-matching:80
          predicates:
            - Path=/matching/**

        - id: user_route
          uri: http://meetatmensa-user:80
          predicates:
            - Path=/user/**

        - id: genai_route
          uri: http://meetatmensa-genai:80
          predicates:
            - Path=/genai/**
