# This configuration file defines the routing rules for the Spring Cloud Gateway
# and specifies the backend services to which requests should be forwarded.
server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: 
                - "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: 
                - "*"
      routes:
        - id: matching_route
          uri: http://meetatmensa-matching:80
          predicates:
            - Path=/api/v2/matching/**

        - id: user_route
          uri: http://meetatmensa-user:80
          predicates:
            - Path=/api/v2/user/**

        - id: genai_route
          uri: http://meetatmensa-genai:80
          predicates:
            - Path=/genai/**
