#k8s/templates/ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "meetatmensa.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "meetatmensa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.gatewayHost }}
        - {{ .Values.ingress.clientHost }}
        - {{ .Values.ingress.monitoringHost }}
      secretName: meetatmensa-tls
#      secretName: meetatmensa-tls
  rules:
    - host: {{ .Values.ingress.gatewayHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.gatewayServiceName }}
                port:
                  number: {{ .Values.gateway.service.port }}
    - host: {{ .Values.ingress.clientHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.clientServiceName }}
                port:
                  number: {{ .Values.client.service.port }}
    - host: {{ .Values.ingress.monitoringHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.monitoringServiceName }}
                port:
                  number: {{ .Values.monitoring.service.port }}
{{- end }}