/*
 * MeetAtMensa
 * This OpenAPI specification defines the endpoints, schemas, and security mechanisms for the Meet@Mensa User micro-service. 
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: devoops@tyrean.mozmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ConversationStarterCollection;
import org.openapitools.client.model.UserCollection;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GenAiApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public GenAiApi() {
        this(Configuration.getDefaultApiClient());
    }

    public GenAiApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getApiV2GenaiConversationStarter
     * @param userCollection Request Conversation starter for these users (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed or contained invalid parameters.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication failed due to missing or invalid OAuth2 token.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource was not found.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getApiV2GenaiConversationStarterCall(@javax.annotation.Nullable UserCollection userCollection, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = userCollection;

        // create path and map variables
        String localVarPath = "/api/v2/genai/conversation-starter";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "auth0" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getApiV2GenaiConversationStarterValidateBeforeCall(@javax.annotation.Nullable UserCollection userCollection, final ApiCallback _callback) throws ApiException {
        return getApiV2GenaiConversationStarterCall(userCollection, _callback);

    }

    /**
     * Request conversation starter
     * Request a series of conversation starter prompts from the GenAI microservice. Provide infomation about users on request.
     * @param userCollection Request Conversation starter for these users (optional)
     * @return ConversationStarterCollection
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed or contained invalid parameters.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication failed due to missing or invalid OAuth2 token.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource was not found.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error </td><td>  -  </td></tr>
     </table>
     */
    public ConversationStarterCollection getApiV2GenaiConversationStarter(@javax.annotation.Nullable UserCollection userCollection) throws ApiException {
        ApiResponse<ConversationStarterCollection> localVarResp = getApiV2GenaiConversationStarterWithHttpInfo(userCollection);
        return localVarResp.getData();
    }

    /**
     * Request conversation starter
     * Request a series of conversation starter prompts from the GenAI microservice. Provide infomation about users on request.
     * @param userCollection Request Conversation starter for these users (optional)
     * @return ApiResponse&lt;ConversationStarterCollection&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed or contained invalid parameters.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication failed due to missing or invalid OAuth2 token.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource was not found.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ConversationStarterCollection> getApiV2GenaiConversationStarterWithHttpInfo(@javax.annotation.Nullable UserCollection userCollection) throws ApiException {
        okhttp3.Call localVarCall = getApiV2GenaiConversationStarterValidateBeforeCall(userCollection, null);
        Type localVarReturnType = new TypeToken<ConversationStarterCollection>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Request conversation starter (asynchronously)
     * Request a series of conversation starter prompts from the GenAI microservice. Provide infomation about users on request.
     * @param userCollection Request Conversation starter for these users (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The request was malformed or contained invalid parameters.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Authentication failed due to missing or invalid OAuth2 token.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The requested resource was not found.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Internal Server Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getApiV2GenaiConversationStarterAsync(@javax.annotation.Nullable UserCollection userCollection, final ApiCallback<ConversationStarterCollection> _callback) throws ApiException {

        okhttp3.Call localVarCall = getApiV2GenaiConversationStarterValidateBeforeCall(userCollection, _callback);
        Type localVarReturnType = new TypeToken<ConversationStarterCollection>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
