#!/bin/bash

set -euo pipefail

# Get the API version of the current spec:
SPEC_VERSION=$(yq '.info.version' api/openapi.yaml)

cat > "api/flags/flags.yaml" <<EOF
# This file is Autogenerated
# Do not change any values manually

# DO NOT CHANGE
info:
  version: $SPEC_VERSION
EOF