/*
 * MeetAtMensa
 * This OpenAPI specification defines the endpoints, schemas, and security mechanisms for the Meet@Mensa User micro-service. 
 *
 * The version of the OpenAPI document: 2.1.4
 * Contact: devoops@tyrean.mozmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ConversationStarter;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Object representing a collection of conversation starters in the Meet@Mensa system.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-01T11:47:31.922653007Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class ConversationStarterCollection {
  public static final String SERIALIZED_NAME_CONVERSATIONS_STARTERS = "conversationsStarters";
  @SerializedName(SERIALIZED_NAME_CONVERSATIONS_STARTERS)
  @javax.annotation.Nonnull
  private List<ConversationStarter> conversationsStarters = new ArrayList<>();

  public ConversationStarterCollection() {
  }

  public ConversationStarterCollection conversationsStarters(@javax.annotation.Nonnull List<ConversationStarter> conversationsStarters) {
    this.conversationsStarters = conversationsStarters;
    return this;
  }

  public ConversationStarterCollection addConversationsStartersItem(ConversationStarter conversationsStartersItem) {
    if (this.conversationsStarters == null) {
      this.conversationsStarters = new ArrayList<>();
    }
    this.conversationsStarters.add(conversationsStartersItem);
    return this;
  }

  /**
   * Get conversationsStarters
   * @return conversationsStarters
   */
  @javax.annotation.Nonnull
  public List<ConversationStarter> getConversationsStarters() {
    return conversationsStarters;
  }

  public void setConversationsStarters(@javax.annotation.Nonnull List<ConversationStarter> conversationsStarters) {
    this.conversationsStarters = conversationsStarters;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationStarterCollection conversationStarterCollection = (ConversationStarterCollection) o;
    return Objects.equals(this.conversationsStarters, conversationStarterCollection.conversationsStarters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conversationsStarters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationStarterCollection {\n");
    sb.append("    conversationsStarters: ").append(toIndentedString(conversationsStarters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("conversationsStarters"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("conversationsStarters"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConversationStarterCollection
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConversationStarterCollection.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConversationStarterCollection is not found in the empty JSON string", ConversationStarterCollection.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConversationStarterCollection.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConversationStarterCollection` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConversationStarterCollection.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("conversationsStarters").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `conversationsStarters` to be an array in the JSON string but got `%s`", jsonObj.get("conversationsStarters").toString()));
      }

      JsonArray jsonArrayconversationsStarters = jsonObj.getAsJsonArray("conversationsStarters");
      // validate the required field `conversationsStarters` (array)
      for (int i = 0; i < jsonArrayconversationsStarters.size(); i++) {
        ConversationStarter.validateJsonElement(jsonArrayconversationsStarters.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConversationStarterCollection.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConversationStarterCollection' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConversationStarterCollection> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConversationStarterCollection.class));

       return (TypeAdapter<T>) new TypeAdapter<ConversationStarterCollection>() {
           @Override
           public void write(JsonWriter out, ConversationStarterCollection value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConversationStarterCollection read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConversationStarterCollection given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConversationStarterCollection
   * @throws IOException if the JSON string is invalid with respect to ConversationStarterCollection
   */
  public static ConversationStarterCollection fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConversationStarterCollection.class);
  }

  /**
   * Convert an instance of ConversationStarterCollection to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

