prometheus:
  namespace: monitoring-womm
  image:
    repository: ghcr.io/aet-devops25/team-devoops/prometheus
    tag: latest
    pullPolicy: Always
  args:
    - "--web.external-url=/prometheus/"
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus/"
    - "--web.console.libraries=/etc/prometheus/console_libraries"
    - "--web.console.templates=/etc/prometheus/consoles"
    - "--web.enable-lifecycle"
  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090
  replicaCount: 1
  # volumes:
  #   - name: prometheus-volume
  #     mountPath: /prometheus
  #     storage: 1Gi 