prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

    # Static configuration instead of ServiceMonitors
    additionalScrapeConfigs:
      - job_name: "gateway"
        static_configs:
          - targets: ["meetatmensa-gateway:80"]
        metrics_path: "/actuator/prometheus"
        scrape_interval: 30s

      - job_name: "matching"
        static_configs:
          - targets: ["meetatmensa-matching:80"]
        metrics_path: "/actuator/prometheus"
        scrape_interval: 30s

      - job_name: "user"
        static_configs:
          - targets: ["meetatmensa-user:80"]
        metrics_path: "/actuator/prometheus"
        scrape_interval: 30s

      - job_name: "genai"
        static_configs:
          - targets: ["meetatmensa-genai:8000"]
        metrics_path: "/metrics"
        scrape_interval: 30s

      - job_name: "client"
        static_configs:
          - targets: ["meetatmensa-client:3000"]
        metrics_path: "/metrics"
        scrape_interval: 30s

  # Disable components that require cluster-wide permissions
  alertmanager:
    enabled: false

  grafana:
    enabled: false

  kubeStateMetrics:
    enabled: false

  nodeExporter:
    enabled: false

  pushgateway:
    enabled: false
