kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  grafana:
    persistence:
      enabled: true
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    additionalDataSources:
      # Loki datasource removed 