# This workflow should deploy meet@mensa to the chair's Rancher Kubernetes cluster every time code is pushed into main branch
name: Continuous Deployment to Kubernetes (CD)

# This workflow is triggered only when called by CI/CD workflow
on:
  workflow_call:

    # Pass KUBECONFIG as a secret
    secrets:
      KUBECONFIG:
        required: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout git repo
    - name: Checkout
      uses: actions/checkout@v4

    # Use Azure's kubectl installation action
    - name: Install Kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: latest

    # Use Azure's helm installation action
    - name: Install Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: latest

    # Copy the details of Kubeconfig to enable authentication with the Rancher cluster
    - name: Load Kubeconfig
      run: |
        mkdir -p ~/.kube
        printf "%s" "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    # Run helm upgrade to upgrade deployment
    - name: Upgrade Deployment with Helm
      run: |
        helm upgrade --install meetatmensa ./deployment/k8s -n devoops