# This workflow handles the Continuous Integration pipeline for MeetAtMensa
name: Continuous Integration (CI)

on:
  # Callable by the CI/CD Action
  workflow_call:

  # Run on push to dev branches
  push:
    branches-ignore: [main]

  # Run on PRs to main
  pull_request:
    branches: [main]

# Cancel running action if another is triggered on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run Update API Spec
  update_api_spec:
    name: Update API Spec
    uses: ./.github/workflows/update_api_spec.yml

  # TODO Add linting

  # Run Java unit tests
  unit_tests:
    name: Run Tests
    uses: ./.github/workflows/java_tests.yml
    needs: update_api_spec

# Skip Pipeline after Deadline due to misconfig
#
#  # Run GenAI module tests
#  genai_tests:
#    name: Run GenAI Tests
#    uses: ./.github/workflows/genai_tests.yml
#    needs: update_api_spec
#    secrets:
#      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#
#  # Run UI tests (unit, integration, and e2e)
#  ui_tests:
#    name: Run UI Tests
#    uses: ./.github/workflows/ui_tests.yml
#    needs: update_api_spec

  # TODO Add Integration Testing

  # Call the docker_build workflow to build and publish images
  build:
    name: Build & Publish Images
    uses: ./.github/workflows/docker_build.yml
    needs: [unit_tests] #now
# Skip Pipeline after Deadline due to misconfig
#    needs: [unit_tests, ui_tests] #previously
