# This workflow builds and publishes the images, then deploys them to the Kubernetes cluster.
# It runs only when code is pushed to the main branch, and is thus considered ready for production.
name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/ci-cd-pipeline-cleanup

jobs:

  # Call the Continuous Integration workflow
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml

  # Call the kubernetes_deploy workflow to deploy to Rancher
  cd_kubernetes:
    name: Continuous Deployment (Kubernetes)
    needs: ci # wait for build to complete before running
    uses: ./.github/workflows/cd_kubernetes.yml
    secrets: # Pass KUBECONFIG to called workflow
      KUBECONFIG: ${{ secrets.KUBECONFIG }}