# This workflow builds and publishes the images, then deploys them to the Kubernetes cluster.
name: Deploy Meet@Mensa

on:
  push:
  # TODO: Set to only run when pushed to main before PR is merged

jobs:

  # Call the docker_build workflow to build and publish images
  build:
    name: Build & Publish Images
    uses: ./.github/workflows/docker_build.yml

  # Call the kubernetes_deploy workflow to deploy to Rancher
  deploy:
    name: Deploy to Kubernetes Cluster
    needs: build
    uses: ./.github/workflows/kubernetes_deploy.yml