# This workflow should deploy meet@mensa to the chair's Rancher Kubernetes cluster every time code is pushed into main branch
name: Deploy to Kubernetes Cluster

# Currently, this workflow can only be triggered manually.
on:
  workflow_dispatch:
  push:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout git repo
    - name: Checkout
      uses: actions/checkout@v4

    # Use Azure's kubectl installation action
    - name: Install Kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: latest

    # Use Azure's helm installation action
    - name: Install Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: latest

    # Copy the details of Kubeconfig to enable authentication with the Rancher cluster
    - name: Load Kubeconfig
      run: | # TODO: I'm unsure what the label and format for the secret containing the kubernetes token is. Will have to ask the Jan on Tuesday.
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    # Run helm upgrade to upgrade deployment
    - name: Upgrade Deployment with Helm
      run: |
        helm upgrade --install meetatmensa ./deployment/k8s -n devoops