name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: "AWS Access Key ID from Learner Lab"
        required: true
        type: string
      aws_secret_access_key:
        description: "AWS Secret Access Key from Learner Lab"
        required: true
        type: string
      aws_session_token:
        description: "AWS Session Token from Learner Lab"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd infrastructure/terraform
          terraform init

      - name: Terraform Apply
        id: terraform
        run: |
          cd infrastructure/terraform
          terraform apply -auto-approve
          echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
        env:
          TF_VAR_aws_access_key: ${{ github.event.inputs.aws_access_key_id }}
          TF_VAR_aws_secret_key: ${{ github.event.inputs.aws_secret_access_key }}
          TF_VAR_aws_session_token: ${{ github.event.inputs.aws_session_token }}

      - name: Copy Docker Compose File From Repo to VM Host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ steps.terraform.outputs.public_ip }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: "deployment/compose.aws.yml"
          target: /home/ubuntu/deployment
          strip_components: 1
          overwrite: true

      - name: SSH to VM and Create .env.prod
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.terraform.outputs.public_ip }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            rm -f .env.prod
            touch .env.prod
            echo "EC2_PUBLIC_IP=${{ steps.terraform.outputs.public_ip }}" >> .env.prod
            echo "CLIENT_HOST=client.${{ steps.terraform.outputs.public_ip }}.nip.io" >> .env.prod
            echo "SERVER_HOST=api.${{ steps.terraform.outputs.public_ip }}.nip.io" >> .env.prod
            echo "PUBLIC_API_URL=https://api.${{ steps.terraform.outputs.public_ip }}.nip.io" >> .env.prod

      - name: SSH to VM and Execute Docker-Compose Up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.terraform.outputs.public_ip }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f deployment/compose.aws.yml --env-file=/home/ubuntu/.env.prod up -d
