apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promtail.fullname" . }}-config
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
    
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log
        pipeline_stages:
          - docker: {} 